FROM postgres:18

# Copy your initialization schema directly into the container's entrypoint folder
# This ensures it runs automatically when the container starts for the first time
COPY ./schema.sql /docker-entrypoint-initdb.d/schema.sql

# Optional: If you need to install any additional tools or extensions, do it here:
# RUN apt-get update && apt-get install -y some-package
